"""Emit the token template library as a TypeScript module.

Shapes are packed to bits: 12 rings x 64 sectors = 768 bits = 24 uint32 words,
base64-encoded. Two reasons beyond size. Matching becomes XOR-and-popcount over
24 words instead of 768 comparisons, which is what makes 111 templates x 64
rotations x 18 tokens affordable on a phone. And 64 sectors is exactly two
uint32 per ring, so rotating a template is a 64-bit rotate of each ring rather
than a per-cell copy.
"""
import base64
import sys

sys.path.insert(0, 'tools')
import numpy as np

import digit_match_probe as D
from board_shots import SHOTS, TRUTH

assert D.SECTORS == 64 and D.RINGS == 12, 'packing assumes 12x64'


def pack(shape):
    """Rows of 64 sectors -> 2 uint32 each, MSB first within each word."""
    words = []
    for ring in range(D.RINGS):
        row = shape[ring]
        for half in range(2):
            w = 0
            for bit in range(32):
                if row[half * 32 + bit]:
                    w |= 1 << (31 - bit)
            words.append(w)
    return np.array(words, dtype='>u4').tobytes()


bank = {n: D.shapes(p, c) for n, (p, c) in SHOTS.items()}
entries = []
for name, faces in bank.items():
    for i, (shape, _red) in sorted(faces.items()):
        entries.append((TRUTH[i], base64.b64encode(pack(shape)).decode(), f'{name} hex{i}'))
entries.sort(key=lambda e: (e[0], e[2]))

counts = {}
for v, _, _ in entries:
    counts[v] = counts.get(v, 0) + 1
print('templates per value:', dict(sorted(counts.items())))
print('total:', len(entries))

lines = ['''/**
 * Number-token templates, harvested from real captures of a real board.
 *
 * GENERATED by tools/emit_library.py — do not edit by hand.
 *
 * Each entry is one photographed token's digit, reduced to ink-or-not on a
 * polar grid of 12 rings x 64 sectors and packed to 24 uint32 words, base64.
 * Sampling is centred and scaled on the DIGIT's own extent, so print size,
 * camera distance and where the token happened to sit all drop out; only the
 * shape of the numeral remains.
 *
 * WHY EXAMPLES RATHER THAN A MODEL OF WHAT A "6" LOOKS LIKE: it is not
 * modelling anything. These are the same tokens, the same ink, photographed
 * under the same kind of light the reader will meet. Measured leave-one-photo-
 * out across seven captures, they read a photo they were not harvested from at
 * 89% overall and 100% precision on what they accept.
 *
 * Every example is kept as its own template rather than averaged into one per
 * value. Two tokens of the same value differ in glare and stroke, and blurring
 * them together loses whichever one would have matched.
 *
 * CAVEAT: every capture is of the SAME physical board. This is validated across
 * photos, not across Catan sets. A differently printed set may need its own
 * examples, which is what `learnedTemplates` in the reader is for.
 */

import { DIGIT_WORDS, unpackShape, type DigitTemplate } from '@/services/vision/digitShape';

/** value, then the packed shape. Source capture noted for traceability. */
const RAW: ReadonlyArray<readonly [number, string]> = [''']
for v, b64, src in entries:
    lines.append(f"  [{v}, '{b64}'], // {src}")
lines.append('''];

export const TOKEN_TEMPLATES: readonly DigitTemplate[] = RAW.map(([value, packed]) => ({
  value,
  bits: unpackShape(packed),
}));

/** Guard against a truncated or hand-edited entry reaching the matcher. */
export const TEMPLATES_ARE_WELL_FORMED = TOKEN_TEMPLATES.every(
  t => t.bits.length === DIGIT_WORDS,
);''')

out = 'artifacts/dice-tracker/services/vision/tokenLibrary.ts'
open(out, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('wrote', out)
